version: "3.8"
services:
  api:
    build: .
    platform: linux/amd64
    image: "registry.gitlab.com/armuro.rey.dev/container-registry/koi-web:1.2.1"
    container_name: koi-web
    network_mode: bridge
    ports:
      - "8006:5000"
    environment:
      - UrlAPI=${UrlAPI}